### ISSUE TITLE
A node like this already exists

### ISSUE THREAD

**Issue by TotallyInformation** [Neonox31/node-red-contrib-date#1]
You do know I guess that there is already a node that does this and more?

node-red-contrib-moment

You can add/subtract date/time intervals as well has handle different locales and timezones and format to whatever you like.

**Comment by Neonox31** [comment]
Hi,

Sure, I'm aware of the existence of `node-red-contrib-moment ` but the node is not able to detect french public holidays. So, I preffered to use my own node adapted to my needs.
The best solution is to split the public holidays detection in a proper node and use `node-red-contrib-moment ` for other date manipulations, but I do not have time for this now.

Thanks for your notification.

**Comment by TotallyInformation** [comment]
ok, no problem. I've not included any holiday processing in contrib-moment as nobody had asked for it and the main thrust was about date/time formatting rather than calculations. However, I would like to add more processing options in the future.

You might consider adding some text to the readme so that other people know when to use your node.
